remote-theme: jekyll-theme-feeling-responsive
plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate

title: Sophia
slogan: Ukrainian Catholicism
description: Everything related to Catholicism in my life.
